public with sharing class PDL_KontaktinformasjonForDoedsbo {

    public PDL_KontaktinformasjonForDoedsboSkifte skifteform{ get;}
    public Date attestutstedelsesdato{ get;}
    public PDL_KontaktinformasjonForDoedsboPerson personSomKontakt{ get;}
    public PDL_KontaktinformasjonForDoedsboAdvokat advokatSomKontakt{ get;}
    public PDL_KontaktinformasjonForDoedsboOrg organisasjonSomKontakt{ get;}
    public PDL_KontaktinformasjonForDoedsboAdresse adresse{ get;}
    public PDL_Folkeregistermetadata folkeregistermetadata{ get;}
    public PDL_Metadata metadata{ get;}

    public PDL_KontaktinformasjonForDoedsbo() {

    }
}
