public with sharing class PDL_HentPerson {

    public PDL_Adressebeskyttelse[] adressebeskyttelse{ get;}
    public PDL_Bostedsadresse[] bostedsadresse{ get;}
    public PDL_DeltBosted[] deltBosted{ get;}
    public PDL_DoedfoedtBarn[] doedfoedtBarn{ get;}
    public PDL_Doedsfall[] doedsfall{ get;}
    public PDL_FalskIdentitet falskIdentitet{ get;}
    public PDL_Foedsel[] foedsel{ get;}
    public PDL_Folkeregisteridentifikator[] folkeregisteridentifikator{ get;}
    public PDL_Folkeregisterpersonstatus[] folkeregisterpersonstatus{ get;}
    public PDL_ForelderBarnRelasjon[] forelderBarnRelasjon{ get;}
    public PDL_Foreldreansvar[] foreldreansvar{ get;}
    public PDL_Fullmakt[] fullmakt{ get;}
    public PDL_Identitetsgrunnlag[] identitetsgrunnlag{ get;}
    public PDL_Kjoenn[] kjoenn{ get;}
    public PDL_Kontaktadresse[] kontaktadresse{ get;}
    public PDL_KontaktinformasjonForDoedsbo[] kontaktinformasjonForDoedsbo{ get;}
    public PDL_Navn[] navn{ get;}
    public PDL_Opphold[] opphold{ get;}
    public PDL_Oppholdsadresse[] oppholdsadresse{ get;}
    public PDL_Sikkerhetstiltak[] sikkerhetstiltak{ get;}
    public PDL_Sivilstand[] sivilstand{ get;}
    public PDL_Statsborgerskap[] statsborgerskap{ get;}
    public PDL_Telefonnummer[] telefonnummer{ get;}
    public PDL_TilrettelagtKommunikasjon[] tilrettelagtKommunikasjon{ get;}
    public PDL_UtenlandskIdentifikasjonsnummer[] utenlandskIdentifikasjonsnummer{ get;}
    public PDL_InnflyttingTilNorge[] innflyttingTilNorge{ get;}
    public PDL_UtflyttingFraNorge[] utflyttingFraNorge{ get;}
    public PDL_VergemaalEllerFremtidsfullmakt[] vergemaalEllerFremtidsfullmakt{ get;}

    public PDL_HentPerson() {
    }
}
