public with sharing class PDL_FalskIdentitet {

    public Boolean erFalsk{ get;}
    public String rettIdentitetVedIdentifikasjonsnummer{ get;}
    public Boolean rettIdentitetErUkjent{ get;}
    public PDL_FalskIdentitetIdentifiserendeInfo rettIdentitetVedOpplysninger{ get;}
    public PDL_Folkeregistermetadata folkeregistermetadata{ get;}
    public PDL_Metadata metadata{ get;}

    public PDL_FalskIdentitet() {

    }
}
