public with sharing class PDL_HentPerson {
    
    public PDL_API_Adressebeskyttelse[] adressebeskyttelse{ get;}
    public PDL_API_Bostedsadresse[] bostedsadresse{ get;}
    public PDL_API_DeltBosted[] deltBosted{ get;}
    public PDL_API_DoedfoedtBarn[] doedfoedtBarn{ get;}
    public PDL_API_Doedsfall[] doedsfall{ get;}
    public PDL_API_FalskIdentitet falskIdentitet{ get;}
    public PDL_API_Foedsel[] foedsel{ get;}
    public PDL_API_Folkeregisteridentifikator[] folkeregisteridentifikator{ get;}
    public PDL_API_Folkeregisterpersonstatus[] folkeregisterpersonstatus{ get;}
    public PDL_API_ForelderBarnRelasjon[] forelderBarnRelasjon{ get;}
    public PDL_API_Foreldreansvar[] foreldreansvar{ get;}
    public PDL_API_Fullmakt[] fullmakt{ get;}
    public PDL_API_Identitetsgrunnlag[] identitetsgrunnlag{ get;}
    public PDL_API_Kjoenn[] kjoenn{ get;}
    public PDL_API_Kontaktadresse[] kontaktadresse{ get;}
    public PDL_API_KontaktinformasjonForDoedsbo[] kontaktinformasjonForDoedsbo{ get;}
    public PDL_API_Navn[] navn{ get;}
    public PDL_API_Opphold[] opphold{ get;}
    public PDL_API_Oppholdsadresse[] oppholdsadresse{ get;}
    public PDL_API_Sikkerhetstiltak[] sikkerhetstiltak{ get;}
    public PDL_API_Sivilstand[] sivilstand{ get;}
    public PDL_API_Statsborgerskap[] statsborgerskap{ get;}
    public PDL_API_Telefonnummer[] telefonnummer{ get;}
    public PDL_API_TilrettelagtKommunikasjon[] tilrettelagtKommunikasjon{ get;}
    public PDL_API_UtenlandskIdentifikasjonsnummer[] utenlandskIdentifikasjonsnummer{ get;}
    public PDL_API_InnflyttingTilNorge[] innflyttingTilNorge{ get;}
    public PDL_API_UtflyttingFraNorge[] utflyttingFraNorge{ get;}
    public PDL_API_VergemaalEllerFremtidsfullmakt[] vergemaalEllerFremtidsfullmakt{ get;}

    public PDL_HentPerson() {

    }
}
