public with sharing class PDL_Vegadresse extends PDL_Adresse {
    // @TestVisible
    // public Long matrikkelId { get; }
    public String husnummer { get; }
    public String husbokstav { get; }
    // @TestVisible
    // public String bruksenhetsnummer { get; }
    public String adressenavn { get; }
    // public String kommunenummer { get; }
    // public String bydelsnummer { get; }
    // public String tilleggsnavn { get; }
    // public String postnummer { get; }
    // public PDL_Koordinater koordinater { get; }

    public PDL_Vegadresse() {
    }
}
