public abstract with sharing class PDL_AdresseType extends PDL_InformationType {
    public PDL_Vegadresse vegadresse { get; }
    public PDL_Matrikkeladresse matrikkeladresse { get; }
    public PDL_UtenlandskAdresse utenlandskAdresse { get; }
    // public PDL_UkjentBosted ukjentBosted { get; }
    // public PDL_Folkeregistermetadata folkeregistermetadata { get; }
    // public PDL_Metadata metadata { get; }
}
