public with sharing class PDL_DeltBostedsadresse {
    public Datetime startdatoForKontrakt{ get;}
    public Datetime sluttdatoForKontrakt{ get;}
    public String coAdressenavn{ get;}
    public PDL_Vegadresse vegadresse{ get;}
    public PDL_Matrikkeladresse matrikkeladresse{ get;}
    public PDL_UkjentBosted ukjentBosted{ get;}
    public PDL_Folkeregistermetadata folkeregistermetadata{ get;}
    public PDL_Metadata metadata{ get;}

    public PDL_DeltBostedsadresse() {

    }
}