public with sharing class NOM_Ressurs {

    public String navident;
    public String personident;
    public NOM_RessursOrgTilknytning orgTilknytning;
    public NOM_LederOrgEnhet lederFor;
    public NOM_RessursLeder ledere;
    public NOM_FolkeregisterPerson folkeregisterPerson;
    public String epost;
    public String visningsnavn;
    public String fornavn;
    public String etternavn;
    public NOM_Telefon telefon;
    public NOM_Sektor sektor;

    public NOM_Ressurs() {

    }
}