name: Automerge Dependabot PRs

on:
  schedule:
    - cron: "30 4 * * 1-5"
  workflow_dispatch:
permissions: {}
concurrency:
  group: automerge-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  automerge:
    permissions:
      contents: write # Required to perform the merge commit
      pull-requests: write # Required to merge PRs (and approve if auto-approve is enabled)
      checks: read # Required to read check runs (update-branch-before-merge)
      statuses: read # Required to read commit statuses (update-branch-before-merge)
    name: Automerge
    uses: navikt/crm-workflows-base/.github/workflows/automergeDependabot.yml@9efb41364aeb8c5f731f397affab1e8c8cb423b1
    with:
      PLATFORM_TOKEN_APP_ID: ${{ vars.PLATFORM_TOKEN_APP_ID }}
    secrets:
      PLATFORM_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PLATFORM_TOKEN_APP_PRIVATE_KEY }}
